[package]

name = "cargo-bot"
version = "0.0.2"
authors = ["seb <seb@ukr.net>"]

[lib]
name = "lib"
path = "src/lib/lib.rs"


[[bin]]
name = "cargo-bot"
path = "src/main.rs"

[dependencies]
rustc-serialize = "*"
